print('Calculadora de IMC básica!')
peso = float(input('Qual é o seu peso? '))
altura = float(input('Qual é a sua altura? '))
imc = peso / (altura ** 2)
print('O seu IMC é {}'.format(imc),end='')
print('!')