print('===Bem vindo ao nosso quarto desafio!===')
v1 = input('Digite algo: ')
print('A classe do valor é',type(v1))
print('O valor é alfa numérico?',v1.isalnum())
print('O valor é alfabético?',v1.isalpha())
print('O valor é numérico?',v1.isnumeric())
print('O valor é decimal?', v1.isdecimal())
print('O valor é todo em maiúsculo?', v1.isupper())
print('O valor é todo em minúsculo?', v1.islower())
print('O valor so tem espaços?', v1.isspace())